field: c35e1a9b-e5ca-43f8-a58e-0a58e1581fbd # Page Sections
fieldLayouts:
  17096a24-ec32-4272-a5c5-fb094775a6a6:
    tabs:
      -
        elements:
          -
            fieldUid: a5b574d0-080f-48eb-9e76-079061ba4126 # Section Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 05abf91c-0d86-484b-97c7-16218f9836ed # Capacity Items
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  05abf91c-0d86-484b-97c7-16218f9836ed: # Capacity Items
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: capacityItems
    instructions: ''
    name: 'Capacity Items'
    searchable: true
    settings:
      addRowLabel: 'Add an Item'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Capacity Item'
                -
                  - handle
                  - capacityItem
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  a5b574d0-080f-48eb-9e76-079061ba4126: # Section Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: ''
    name: 'Section Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: capacityList
name: 'Capacity List'
sortOrder: 3
