field: 3e8173e2-82d1-4c5e-8d56-622c2f629efe # Content
fieldLayouts:
  a1af0c9c-4cc4-4360-9e36-f5aacd96b3fc:
    tabs:
      -
        elements:
          -
            fieldUid: 9a3aa619-e636-45f5-a6f7-0b472980c0bb # Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9a3aa619-e636-45f5-a6f7-0b472980c0bb: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: sectionTitle
    instructions: ''
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sectionTitle
name: 'Section Title'
sortOrder: 1
