field: c35e1a9b-e5ca-43f8-a58e-0a58e1581fbd # Page Sections
fieldLayouts:
  b4ae97f7-a70b-4203-aa01-72fbcc6549b5:
    tabs:
      -
        elements:
          -
            fieldUid: 999c8e96-eedc-42d0-9936-1ed24f6a1237 # Text
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  999c8e96-eedc-42d0-9936-1ed24f6a1237: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: kadops.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: sectionText
name: 'Section Text'
sortOrder: 2
