field: c35e1a9b-e5ca-43f8-a58e-0a58e1581fbd # Page Sections
fieldLayouts:
  69ebd490-2e94-42e6-8060-0dd0b0ce548c:
    tabs:
      -
        elements:
          -
            fieldUid: b0f72810-cb75-4db1-9846-ad819a9d3d5f # Section Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2fd7d0b2-a8af-43b5-b48d-8aed11fb975b # Service
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2fd7d0b2-a8af-43b5-b48d-8aed11fb975b: # Service
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: service
    instructions: ''
    name: Service
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - b40b9c43-9e56-46a1-86b1-1a6e8dee9665 # Service Name
            -
              __assoc__:
                -
                  - width
                  - 40%
          -
            - 7bedad13-023a-4d2e-a2ea-93354c6af2df # Service Image
            -
              __assoc__:
                -
                  - width
                  - 20%
          -
            - 67ffad80-6f58-4aa0-adce-b663ccddcfb1 # Link?
            -
              __assoc__:
                -
                  - width
                  - 20%
      contentTable: '{{%stc_8_service}}'
      fieldLayout: table
      maxRows: ''
      minRows: '1'
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: none
      selectionLabel: 'Add a Service'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  b0f72810-cb75-4db1-9846-ad819a9d3d5f: # Section Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: serviceSectionTitle
    instructions: ''
    name: 'Section Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: serviceslisting
name: ServicesList
sortOrder: 5
