field: c35e1a9b-e5ca-43f8-a58e-0a58e1581fbd # Page Sections
fieldLayouts:
  3b94b281-abe7-462f-a410-051f457b14b1:
    tabs:
      -
        elements:
          -
            fieldUid: 96aa048d-6854-4079-a4bb-19af7c170d9f # Add Images
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  96aa048d-6854-4079-a4bb-19af7c170d9f: # Add Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: addImages
    instructions: ''
    name: 'Add Images'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add an Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
        - 'volume:49dabed7-207d-4087-9227-a18660a3b4c2' # Panda
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: supportingImages
name: 'Supporting Images'
sortOrder: 4
