allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  3d0cb834-f3e7-4bf1-91b4-fd6f957168e6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6e33bb60-e268-4870-bc46-b4fc8094502e
            handle: null
            instructions: null
            label: Logo
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12a563b6-386e-4d9f-9ca4-ecafb430c754
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bf857587-fa36-45ac-8f9c-8d799f0ca1e0
        userCondition: null
    thumbFieldKey: null
handle: brandBlock
hasTitleField: false
icon: null
name: 'Brand Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
