allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  5cf24184-92fd-42f0-9489-2b8ceebdcd59:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 92c21d7c-f3a9-4219-8f54-505098156f65 # Profile - Profile Picture
            handle: profilePicture
            instructions: null
            label: 'Profile Picture'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a35e4cf-0efc-40a6-b96d-61b515f0a23c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 964636a0-9dd8-4e64-8a82-b2870e2e12af
            handle: firstName
            instructions: null
            label: 'First Name'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a160c9d-6e50-471f-9823-08e9dd1204d9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 85bd7c4f-aae4-456f-af33-31b87ab82276
            handle: surname
            instructions: null
            label: Surname
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90620941-1a74-42f8-a464-35906dcbee06
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: cf7b0e33-7c76-4132-bb68-aacf438ed2c7
            handle: positionTitle
            instructions: null
            label: Position/Title
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72f4e712-3045-445d-adf9-476b54a0ce4c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5e131149-b2d7-423b-b1ab-52ef8e34c208
            handle: emailAddress
            instructions: null
            label: 'Email Address'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dac3b989-f838-4e70-a671-2450424c28bf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d682feb0-05b9-4c03-b3f6-33bf5e8b07ee
            handle: linkedinLink
            instructions: null
            label: 'LinkedIn Link'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89010f51-970d-4ae7-9ff5-af45dd45c581
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e2222c2-d313-4202-b4db-9f74fc4df01f
        userCondition: null
    thumbFieldKey: null
handle: profileBlock
hasTitleField: false
icon: null
name: 'Profile Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
