columnSuffix: null
contentColumnType: string
handle: caseStudyImages
instructions: null
name: 'Case Study Images'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:49dabed7-207d-4087-9227-a18660a3b4c2'
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9'
  restrictedLocationSubpath: null
  selectionLabel: 'Add an Image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:49dabed7-207d-4087-9227-a18660a3b4c2'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
