columnSuffix: null
contentColumnType: string
fieldGroup: 3ef47ed8-7e10-4143-b599-cadbdc4ed33b # Common
handle: contentBuilder
instructions: ''
name: Content
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentbuilder}}'
  maxBlocks: ''
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
