columnSuffix: null
handle: heroOverlayText
instructions: null
name: 'Hero - Hero Overlay Text'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 041c8c55-9d95-430b-8599-a312f5a113dc # Kadops
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
