columnSuffix: null
contentColumnType: text
handle: override
instructions: null
name: 'Override Global SEO Per Page'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
