columnSuffix: null
contentColumnType: text
fieldGroup: 64c30549-98c7-4f27-b59e-59659739ca75 # Capabilities
handle: pageIntroduction
instructions: ''
name: 'Page Introduction'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: site
type: craft\redactor\Field
