columnSuffix: null
contentColumnType: text
fieldGroup: 3ef47ed8-7e10-4143-b599-cadbdc4ed33b # Common
handle: pageTitle
instructions: ''
name: 'Page Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
