field: df6900ca-95b7-4dd4-8f9b-b4457d51e3d6 # Policy Documents
fieldLayouts:
  4f308347-8869-452c-9294-34ab46422219:
    tabs:
      -
        elements:
          -
            fieldUid: e5fefffd-14d4-49f6-afba-ff31c9439344 # Document title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d734bee2-d132-4204-89a0-edec02ba9213 # Document Upload
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d734bee2-d132-4204-89a0-edec02ba9213: # Document Upload
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: documentUpload
    instructions: ''
    name: 'Document Upload'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:49dabed7-207d-4087-9227-a18660a3b4c2' # Panda
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add File'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:49dabed7-207d-4087-9227-a18660a3b4c2' # Panda
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e5fefffd-14d4-49f6-afba-ff31c9439344: # Document title
    columnSuffix: null
    contentColumnType: string(80)
    fieldGroup: null
    handle: documentTitle
    instructions: ''
    name: 'Document title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: 20
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
