field: 318ceac4-1f0c-4b8b-b3db-39faa69fd25d # Hero
fieldLayouts:
  fe7990c5-245e-446c-b37a-87587e10471b:
    tabs:
      -
        elements:
          -
            fieldUid: 4e5e3aa1-5835-4980-ba6c-9f87b1cfa94a # Hero Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2440d605-4546-4ad3-84b8-61d02fd259f6 # Hero Overlay Text
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4e5e3aa1-5835-4980-ba6c-9f87b1cfa94a: # Hero Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heroImage
    instructions: ''
    name: 'Hero Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add a hero image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2440d605-4546-4ad3-84b8-61d02fd259f6: # Hero Overlay Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heroOverlayText
    instructions: ''
    name: 'Hero Overlay Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: kadops.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
