field: 7bfb3391-5edc-42d9-a58a-e34712a21e69 # Service Capabilities
fieldLayouts:
  a88271cc-1751-4a16-9983-d545ab3e53da:
    tabs:
      -
        elements:
          -
            fieldUid: 87ff484a-e88c-48b0-8815-a96efaf1d6f0 # Service Title
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2bf32af3-2504-449b-9e7f-9a3548253ff8 # Service Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 257dfff7-f54a-4ee8-81fb-635a85dda547 # Service Summary
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 31f1bd89-9b4e-48f6-9025-f5459acc810f # Service Points
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2bf32af3-2504-449b-9e7f-9a3548253ff8: # Service Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: serviceImage
    instructions: ''
    name: 'Service Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add a service image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  31f1bd89-9b4e-48f6-9025-f5459acc810f: # Service Points
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: servicePoints
    instructions: ''
    name: 'Service Points'
    searchable: true
    settings:
      addRowLabel: 'Add a point'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Service Point'
                -
                  - handle
                  - servicePoint
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  87ff484a-e88c-48b0-8815-a96efaf1d6f0: # Service Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: serviceTitle
    instructions: ''
    name: 'Service Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  257dfff7-f54a-4ee8-81fb-635a85dda547: # Service Summary
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: serviceSummary
    instructions: ''
    name: 'Service Summary'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '3'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
