field: cfb263fc-777f-4e2c-806b-beefa017645d # Brand
fieldLayouts:
  3d0cb834-f3e7-4bf1-91b4-fd6f957168e6:
    tabs:
      -
        elements:
          -
            fieldUid: 6e33bb60-e268-4870-bc46-b4fc8094502e # Logo
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6e33bb60-e268-4870-bc46-b4fc8094502e: # Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logo
    instructions: ''
    name: Logo
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:4b87641c-dafb-4624-82e2-fa956cbcfb67' # Stat
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:504a9970-e732-4891-a6f3-66f1e99d8ae9' # Kadops
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:4b87641c-dafb-4624-82e2-fa956cbcfb67' # Stat
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
