field: 091b9d19-5686-40f4-93a4-ad85dc15777a # Company Information
fieldLayouts:
  42b0855f-f646-4eec-8af6-f5b9f83f2d0f:
    tabs:
      -
        elements:
          -
            fieldUid: 1cfcc26c-9d2a-42d0-b6c7-155d7c010a92 # Address
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8ec8a84e-28c6-4e2f-a346-0bbcbbd546dc # Company Reg
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 000dc138-de3d-4948-bec2-496f89984e1d # Contacts
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  000dc138-de3d-4948-bec2-496f89984e1d: # Contacts
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: contacts
    instructions: ''
    name: Contacts
    searchable: true
    settings:
      addRowLabel: 'Add a Contact'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Name
                -
                  - handle
                  - name
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Number
                -
                  - handle
                  - number
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - Email
                -
                  - handle
                  - email
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  1cfcc26c-9d2a-42d0-b6c7-155d7c010a92: # Address
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: ''
    name: Address
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  8ec8a84e-28c6-4e2f-a346-0bbcbbd546dc: # Company Reg
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: companyReg
    instructions: ''
    name: 'Company Reg'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
