currLabel: 'Plugin Store'
customIcon: null
enabled: true
handle: plugin-store
icon: plugin
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: false
parent: null
prevLabel: 'Plugin Store'
prevLevel: null
prevParent: null
prevUrl: plugin-store
sortOrder: 10
subnavBehaviour: null
type: craft
url: plugin-store
