currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: assets
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: false
parent: null
prevLabel: Assets
prevLevel: null
prevParent: null
prevUrl: assets
sortOrder: 3
subnavBehaviour: null
type: craft
url: assets
