currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: assets
layout: 2f0cdc40-8dac-4d29-b2d1-3ee2c5b5d666 # Staff
level: 1
newWindow: false
parentId: null
prevLabel: Assets
prevLevel: null
prevParentId: null
prevUrl: assets
sortOrder: 3
type: craft
url: assets
