currLabel: 'Field Manager'
customIcon: null
enabled: true
handle: field-manager
icon: /Users/martinsmith/Documents/Sites/panda-kadops/httpdocs/craft/vendor/verbb/field-manager/src/icon-mask.svg
layoutId: 2
level: 1
newWindow: false
parentId: null
prevLabel: 'Field Manager'
prevLevel: null
prevParentId: null
prevUrl: field-manager
sortOrder: 5
type: ''
url: field-manager
