currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layoutId: 2
level: 1
newWindow: false
parentId: null
prevLabel: Entries
prevLevel: null
prevParentId: null
prevUrl: entries
sortOrder: 1
type: craft
url: entries
