currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: false
parentId: null
prevLabel: Entries
prevLevel: null
prevParentId: null
prevUrl: entries
sortOrder: 1
type: craft
url: entries
