currLabel: Freeform
customIcon: null
enabled: true
handle: freeform
icon: /Users/martinsmith/Documents/Sites/panda-kadops/httpdocs/craft/vendor/solspace/craft-freeform/src/icon-mask.svg
layoutId: 2
level: 1
newWindow: false
parentId: null
prevLabel: Freeform
prevLevel: null
prevParentId: null
prevUrl: freeform
sortOrder: 6
type: ''
url: freeform
