currLabel: Globals
customIcon: null
enabled: '1'
handle: globals
icon: globe
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: '0'
parentId: null
prevLabel: Globals
prevLevel: null
prevParentId: null
prevUrl: globals
sortOrder: '2'
type: ''
url: globals
