currLabel: Globals
customIcon: null
enabled: true
handle: globals
icon: globe
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: false
parent: null
prevLabel: Globals
prevLevel: null
prevParent: null
prevUrl: globals
sortOrder: 2
subnavBehaviour: null
type: null
url: globals
