currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: '@app/icons/graphql.svg'
layoutId: 2
level: 1
newWindow: false
parentId: null
prevLabel: GraphQL
prevLevel: null
prevParentId: null
prevUrl: graphql
sortOrder: 7
type: craft
url: graphql
