currLabel: GraphQL
customIcon: null
enabled: false
handle: graphql
icon: '@app/icons/graphql.svg'
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: null
prevParent: null
prevUrl: graphql
sortOrder: 7
subnavBehaviour: null
type: craft
url: graphql
