currLabel: Settings
customIcon: null
enabled: '1'
handle: settings
icon: settings
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: '0'
parentId: null
prevLabel: Settings
prevLevel: null
prevParentId: null
prevUrl: settings
sortOrder: '9'
type: craft
url: settings
