currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: 2f0cdc40-8dac-4d29-b2d1-3ee2c5b5d666 # Staff
level: 1
newWindow: false
parentId: null
prevLabel: Settings
prevLevel: null
prevParentId: null
prevUrl: settings
sortOrder: 9
type: craft
url: settings
