currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: null
prevParent: null
prevUrl: settings
sortOrder: 9
subnavBehaviour: null
type: craft
url: settings
