currLabel: Tokens
customIcon: null
enabled: true
handle: tokens
icon: null
layout: 2f0cdc40-8dac-4d29-b2d1-3ee2c5b5d666 # Staff
level: 2
newWindow: false
parent: 19a515d3-89b0-4b3a-84ff-fd7c7599281f
prevLabel: Tokens
prevLevel: 2
prevParent: 19a515d3-89b0-4b3a-84ff-fd7c7599281f
prevUrl: graphql/tokens
sortOrder: 0
subnavBehaviour: null
type: null
url: graphql/tokens
