currLabel: Users
customIcon: null
enabled: '0'
handle: users
icon: users
layout: 1b2fd43c-2000-42df-b5aa-0c4c7609c574 # Default
level: 1
newWindow: '0'
parentId: null
prevLabel: Users
prevLevel: null
prevParentId: null
prevUrl: users
sortOrder: '4'
type: craft
url: users
