currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: tool
layoutId: 2
level: 1
newWindow: false
parentId: null
prevLabel: Utilities
prevLevel: null
prevParentId: null
prevUrl: utilities
sortOrder: 8
type: craft
url: utilities
