defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 791a54fd-182a-4eca-b677-a52ea1ff20ad # Additional Pages
handle: additionalPages
maxAuthors: 1
name: 'Additional Pages'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  08101c32-d8eb-4be0-ae85-8bef7fa172b6: # Panda Engineering
    enabledByDefault: true
    hasUrls: true
    template: generic
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: ac18ad09-f22d-4416-a53e-e36401d54147
type: structure
