defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 49baa156-b43e-4e99-9769-48166a3e4fbb # Capability
  -
    uid: bfcd7586-50fc-4927-800f-d7f798054851 # Overview
handle: areasOfCapability
maxAuthors: 1
name: 'Areas of Capability'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: none
siteSettings:
  08101c32-d8eb-4be0-ae85-8bef7fa172b6: # Panda Engineering
    enabledByDefault: true
    hasUrls: true
    template: _areas/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: 9894632d-b6d3-4389-9654-c481aa7dfd0d
type: structure
