defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9e43eb97-3023-4a81-bf7a-25709c76b78b # Images and Text Study
  -
    uid: 9ebe2d4e-07f9-4fd3-8655-0b6ebcff6a31 # Images Only Study
  -
    handle: entype_overview
    uid: d7c35450-613e-4943-9003-ef28eaa6fd69 # Overview
handle: pandaGallery
maxAuthors: 1
name: Gallery
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  08101c32-d8eb-4be0-ae85-8bef7fa172b6: # Panda Engineering
    enabledByDefault: true
    hasUrls: true
    template: _gallery/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 2
  uid: a7373c69-0118-4077-aae0-2270ee8787c8
type: structure
